version: "3"

services:
  srv-back:
    build: backend-app
    container_name: game2-back
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - ./backend-app/.:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"

  srv-front:
    build: frontend-app
    container_name: game2-front
    entrypoint: ./.docker/entrypoint.sh
    ports:
      - "3001:3000"
    volumes:
      - ./frontend-app/.:/home/node/app
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    depends_on:
      - srv-back
