apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app-route
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app-route
  template:
    metadata:
      labels:
        app: backend-app-route
    spec:
      containers:
        - name: backend-app-route
          image: francisrod01/desafio-2_srv-back:latest
          ports:
            - containerPort: 3000
