apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app-route
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app-route
  template:
    metadata:
      labels:
        app: frontend-app-route
    spec:
      containers:
        - name: frontend-app-route
          image: francisrod01/desafio-2_srv-front:latest
          ports:
            - containerPort: 80
